version: '3'

services:
  mysql:
      image: mysql:latest
      container_name: mysql-container
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./mysql-data:/var/lib/mysql
      ports:
        - "3306:3306"

  nodejs:
    image: node:latest
    contatiner_name: nodejs-container
    working_dir: /app
    volumes:
      - ./your-nodejs-app:/app
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=database_name

volumes:
  mysql-data: